In [1]:
import pandas as pd

In [2]:
path = '/content/drive/MyDrive/tesseract/labeled_data.csv'
data = pd.read_csv(path)

In [3]:
data.head()

Unnamed: 0  count  hate_speech  offensive_language  neither  class  \
0           0      3            0                   0        3      2   
1           1      3            0                   3        0      1   
2           2      3            0                   3        0      1   
3           3      3            0                   2        1      1   
4           4      6            0                   6        0      1   

                                               tweet  
0  !!! RT @mayasolovely: As a woman you shouldn't...  
1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...  
2  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...  
3  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...  
4  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24783 entries, 0 to 24782
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   Unnamed: 0          24783 non-null  int64 
 1   count               24783 non-null  int64 
 2   hate_speech         24783 non-null  int64 
 3   offensive_language  24783 non-null  int64 
 4   neither             24783 non-null  int64 
 5   class               24783 non-null  int64 
 6   tweet               24783 non-null  object
dtypes: int64(6), object(1)
memory usage: 1.3+ MB


In [5]:
data.nunique()

Unnamed: 0            24783
count                     5
hate_speech               8
offensive_language       10
neither                  10
class                     3
tweet                 24783
dtype: int64

In [6]:
def no_of_items(column):
  return data[column].unique()


In [7]:
no_of_items("hate_speech")

array([0, 1, 2, 3, 4, 6, 5, 7])

In [8]:
no_of_items("class")

array([2, 1, 0])

In [9]:
data["hate_speech"].value_counts()

hate_speech
0    19790
1     3419
2     1251
3      287
4       21
5        7
6        5
7        3
Name: count, dtype: int64

In [10]:
data['tweet'][data['hate_speech'] == 6]

3404     @Hovaa_ ya I know all the slang I'm racist I h...
3869       @L1LTR4P fucking losers wetbacks #SorryNotSorry
6378     @kcSnowWhite7 @SamSaunders42 don't forget napp...
15809    RT @JihadistJoe: We Muslims have no military h...
19136    RT @iBeZo: Stupid fucking nigger LeBron. You f...
Name: tweet, dtype: object

In [11]:
!pip install datasets

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 542.0/542.0 kB 11.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 18.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 25.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 20.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 401.2/401.2 kB 42.9 MB/s eta 0:00:00
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface-hub 0.20.3
    Uninstalling huggingface-hub-0.20.3:
      Successfully uninstalled huggingface-hub-0.20.3


In [12]:
from transformers import TFAutoModel,AutoTokenizer
from datasets import load_dataset
import tensorflow as tf

In [13]:
model = TFAutoModel.from_pretrained("bert-base-uncased")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

In [14]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [15]:
data = load_dataset('SetFit/emotion')

Repo card metadata block was not found. Setting CardData to empty.


Generating train split:   0%|          | 0/16000 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/2000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/2000 [00:00<?, ? examples/s]

In [16]:
type(data)

datasets.dataset_dict.DatasetDict

In [17]:
data

DatasetDict({
    train: Dataset({
        features: ['text', 'label', 'label_text'],
        num_rows: 16000
    })
    validation: Dataset({
        features: ['text', 'label', 'label_text'],
        num_rows: 2000
    })
    test: Dataset({
        features: ['text', 'label', 'label_text'],
        num_rows: 2000
    })
})

In [18]:
def tokenize(batch):
  return tokenizer(batch['text'],padding = True,truncation = True)

In [19]:
emotions_encoded = data.map(tokenize , batched = True, batch_size = None)

Map:   0%|          | 0/16000 [00:00<?, ? examples/s]

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

In [20]:

emotions_encoded

DatasetDict({
    train: Dataset({
        features: ['text', 'label', 'label_text', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 16000
    })
    validation: Dataset({
        features: ['text', 'label', 'label_text', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 2000
    })
    test: Dataset({
        features: ['text', 'label', 'label_text', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 2000
    })
})

In [21]:
emotions_encoded.set_format('tf',
                            columns=['input_ids', 'attention_mask', 'token_type_ids', 'label'])
batch_size = 64
def order(inp):
  data = list(inp.values())
  return {"input_ids":data[1],
          "attention_mask" : data[2],
          "token_type_ids" : data[3]
          },data[0]

train_dataset = tf.data.Dataset.from_tensor_slices(emotions_encoded['train'][:])
train_dataset = train_dataset.batch(batch_size).shuffle(1000)
train_dataset = train_dataset.map(order,num_parallel_calls = tf.data.AUTOTUNE)

test_dataset = tf.data.Dataset.from_tensor_slices(emotions_encoded['test'][:])
test_dataset = test_dataset.batch(batch_size).shuffle(1000)
test_dataset = test_dataset.map(order,num_parallel_calls = tf.data.AUTOTUNE)

validation_dataset = tf.data.Dataset.from_tensor_slices(emotions_encoded['validation'][:])
validation_dataset = validation_dataset.batch(batch_size).shuffle(1000)
validation_dataset = validation_dataset.map(order,num_parallel_calls = tf.data.AUTOTUNE)

In [22]:
train_dataset.take(1)

<_TakeDataset element_spec=({'input_ids': TensorSpec(shape=(None, 87), dtype=tf.int64, name=None), 'attention_mask': TensorSpec(shape=(None, 87), dtype=tf.int64, name=None), 'token_type_ids': TensorSpec(shape=(None, 87), dtype=tf.int64, name=None)}, TensorSpec(shape=(None,), dtype=tf.int64, name=None))>

In [23]:
inp,out = next(iter(train_dataset))
print(inp,out)

{'input_ids': <tf.Tensor: shape=(64, 87), dtype=int64, numpy=
array([[  101,  1045,  2514, ...,     0,     0,     0],
       [  101, 10047,  4133, ...,     0,     0,     0],
       [  101,  1045,  2288, ...,     0,     0,     0],
       ...,
       [  101,  1045,  2467, ...,     0,     0,     0],
       [  101,  1045,  8271, ...,     0,     0,     0],
       [  101, 10047,  3110, ...,     0,     0,     0]])>, 'attention_mask': <tf.Tensor: shape=(64, 87), dtype=int64, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])>, 'token_type_ids': <tf.Tensor: shape=(64, 87), dtype=int64, numpy=
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]])>} tf.Tensor(
[1 1 1 4 4 1 1 3 4 0 0 1 3 4 0

In [24]:
class BertClassification(tf.keras.Model):
  def __init__(self,bert_model,num_classes):
    super().__init__()
    self.bert_model = bert_model
    self.num_classes = tf.keras.layers.Dense(num_classes,activation = 'softmax')

  def call(self,inputs):
    x = self.bert_model(inputs)[1]
    return self.num_classes(x)


In [25]:
classifier = BertClassification(model,num_classes = 6)

classifier.compile(optimizer = tf.keras.optimizers.Adam(learning_rate = 1e-5),
                   loss = tf.keras.losses.SparseCategoricalCrossentropy(),
                   metrics = ['accuracy'])

In [26]:
history = classifier.fit(train_dataset,epochs = 3,verbose = 1)

Epoch 1/3
250/250 [==============================] - 368s 1s/step - loss: 0.9718 - accuracy: 0.6498
Epoch 2/3
250/250 [==============================] - 286s 1s/step - loss: 0.2688 - accuracy: 0.9047
Epoch 3/3
250/250 [==============================] - 284s 1s/step - loss: 0.1509 - accuracy: 0.9365


In [27]:
classifier.evaluate(test_dataset)

32/32 [==============================] - 19s 281ms/step - loss: 0.1715 - accuracy: 0.9220


[0.17147448658943176, 0.921999990940094]